export default {
  addIcon: "./assets/icons/thread-add-light.svg",
  codeIcon: "./assets/icons/code.png",
  codeEditorIcon: "./assets/icons/code-editor.svg",
  userIcon: "./assets/icons/user.svg",
  lockIcon: "./assets/icons/lock.svg",
  emailIcon: "./assets/icons/email.svg",
  usernameIcon: "./assets/icons/username.svg",
  confettiBg: "./assets/img/confetti_bg.png",
  devImg: "./assets/img/devimg.jpg",
  notebookTutorial: "./assets/img/addnotebook.png",
  notebookTutorialModal: "./assets/img/addnotebook_modal.png",
  addedNotebookTutorial: "./assets/img/added_notebook.png",
  addThreadSelectChannel: "./assets/img/addthread_select_channel.png",
  addThreadNewButton: "./assets/img/addthread_select_button.png",
  addThreadSetTitle: "./assets/img/addthread_set_title.png",
  openWorkspaceMenu: "./assets/img/openworkspace_menu.png",
  openWorkspaceDialogue: "./assets/img/openworkspace_dialogue.png",
  openWorkspaceFinal: "./assets/img/openworkspace_final.png",
  saveWorkspaceMenu: "./assets/img/saveworkspace_menu.png",
  saveWorkspaceDialogue: "./assets/img/saveworkspace_dialogue.png",
  saveWorkspaceNotif: "./assets/img/saveworkspace_notif.png",
  logoIcon: "./assets/icons/logo.png"
};
